global_frame: odom

rolling_window: true
publish_frequency: 2.0

width: 5.0
height: 5.0
resolution: 0.1

plugins:
 - {name: obstacles,  type: "costmap_2d::ObstacleLayer"}
 - {name: inflater,   type: "costmap_2d::InflationLayer"}
