global_frame: map

update_frequency: 5.0
publish_frequency: 2.0
static_map: false
rolling_window: true
width: 20.0
height: 20.0
resolution: 0.1

plugins:
 - {name: obstacles,  type: "costmap_2d::ObstacleLayer"}
 - {name: inflater,   type: "costmap_2d::InflationLayer"}

