robot_base_frame: base_link

transform_tolerance: 0.5

footprint: [[0.25, 0.25], [0.25, -0.25], [-0.4,-0.25], [-0.5, 0.25]]
inflation_radius: 3.0
inflater:
  #footprint: [[0.15, 0.15], [0.15, -0.15], [-0.4,-0.15], [-0.4, 0.15]]
  inflation_radius: 3
  cost_scaling_factor: 5

obstacles:
  observation_sources: base_scan
  base_scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    obstacle_range: 3.0
    raytrace_range: 5.0
    min_obstacle_height: 0.1
    max_obstacle_height: 1.0

