global_frame: map
rolling_window: true
track_unknown_space: true
width: 20.0
height: 20.0
resolution: 0.1


plugins:
  - {name: obstacles,  type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,               type: "costmap_2d::InflationLayer"}
