robot_base_frame: base_link

transform_tolerance: 0.5

footprint: [[0.15, 0.15], [0.15, -0.15], [-0.4,-0.15], [-0.4, 0.15]]
inflater:
  footprint: [[0.15, 0.15], [0.15, -0.15], [-0.4,-0.15], [-0.4, 0.15]]
  inflation_radius: 2.80

obstacles:
  observation_sources: base_scan
  base_scan:
    data_type: LaserScan
    topic: scan
    marking: true
    clearing: true
    obstacle_range: 6.0
    raytrace_range: 10.0
    min_obstacle_height: -1.0
    max_obstacle_height: 1.0

