# Planner selection
base_global_planner: "navfn/NavfnROS"
base_local_planner: "teb_local_planner/TebLocalPlannerROS"

# Recovery behaviors
recovery_behavior_enabled: false
recovery_behaviors:
  - name: "conservative_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
  - name: "rotate_recovery"
    type: "rotate_recovery/RotateRecovery"
  - name: "aggressive_reset"
    type: "clear_costmap_recovery/ClearCostmapRecovery"
conservative_reset:
  reset_distance: 3.0
rotate_recovery:
  frequency: 20.0
  sim_granularity: 0.017
aggressive_reset: 
  reset_distance: 0.5

# Oscillation
oscillation_timeout: 1000.0
oscillation_distance: 0.5

# Global planner
planner_frequency: 0.0
planner_patience: 5.0
NavfnROS:
  allow_unknown: true  # TODO: investigate this
  default_tolerance: 0.0
  # do not restrict planner
  planner_window_x: 0.0
  planner_window_y: 0.0
  # debug
  visualize_potential: false

# Local planner
controller_frequency: 5.0
controller_patience: 15.0

TebLocalPlannerROS:

  # acceleration limits - should match those defined in velocity_smoother.cfg
  acc_lim_x: 0.5
  acc_lim_y: 0.7
  acc_lim_theta: 2.0
  max_vel_x: 0.4
  max_vel_x_backwards: 0.1
  max_vel_y: 0.0
  max_vel_theta: 2.0

  xy_goal_tolerance: 1.0
  yaw_goal_tolerance: 0.78
    
