waypoints:

  - name: nav_area
    frame_id: map
    pose: 
      position: 
        x: 0.72312015295
        y: -1.86154580116
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: -0.121883077663
        w: 0.99254446519

  - name: fire_exit
    frame_id: map
    pose: 
      position: 
        x: 4.45354413986
        y: -2.76388669014
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: -0.689105282828
        w: 0.72466123753
  
  - name: kashyaps_office
    frame_id: map
    pose: 
      position: 
        x: 6.61821556091
        y: -11.0769262314
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: -0.541073237929
        w: 0.840975475979

  - name: kitchen_north_facing
    frame_id: map
    pose: 
      position: 
        x: 8.77369785309
        y: -20.9692077637
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: -0.713797964781
        w: 0.700351672715

  - name: kitchen_south_facing
    frame_id: map
    pose: 
      position: 
        x: 8.75728034973
        y: -20.9415550232
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.711494891124
        w: 0.702691269267

  - name: design_north_facing
    frame_id: map
    pose: 
      position: 
        x: 5.71335840225
        y: -30.3458595276
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: -0.704630674452
        w: 0.709574247434

  - name: design_south_facing
    frame_id: map
    pose: 
      position: 
        x: 5.73911523819
        y: -30.436882019
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.70326188497
        w: 0.710930883524

  - name: vehicle_team
    frame_id: map
    pose: 
      position: 
        x: 10.3795681
        y: -40.6453361511
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: -0.495644835113
        w: 0.868525300395

  - name: benji_desk
    frame_id: map
    pose: 
      position: 
        x: 9.69009304047
        y: -9.30712604523
        z: 0.0
      orientation: 
        x: 0.0
        y: 0.0
        z: 0.880087585499
        w: 0.474811375023


trajectories:
  - name: office_patrol
    waypoints:
    - nav_area
    - fire_exit
    - kashyaps_office
    - kitchen_north_facing
    - design_north_facing
    - vehicle_team
    - design_south_facing
    - kitchen_south_facing
    - benji_desk
    - nav_area
