waypoints:

  - name: tims_desk
    frame_id: map
    pose:
      position:
        x: 0.2
        y: -0.37
        z: 0.0
      orientation:
        x: 0
        y: 0
        z: -0.644
        w: 0.765

  - name: fire_exit
    frame_id: map
    pose:
      position:
        x: -4.23
        y: -2.17
        z: 0.0
      orientation:
        x: 0
        y: 0
        z: 0.74
        w: 0.672
  
  - name: kashyaps_office
    frame_id: map
    pose:
      position:
        x: -3.12
        y: 6.94
        z: 0.0
      orientation:
        x: 0
        y: 0
        z: 0.691
        w: 0.722

  - name: outside_kitchen
    frame_id: map
    pose:
      position:
        x: -0.229
        y: 15.887
        z: 0.0
      orientation:
        x: 0
        y: 0
        z: 0.946
        w: 0.325


trajectories:
  - name: office_patrol
    waypoints:
    - tims_desk
    - fire_exit
    - kashyaps_office
    - outside_kitchen
    - kashyaps_office
    - fire_exit
    - tims_desk
